### ISSUE TITLE
Button list (Left side Icon)

### ISSUE THREAD

**Issue by ognif** [martijnkoopman/Qt-Ribbon-Widget#1]
Is it possible to do a button list, with small left side icons, like a common Ribbon Interface has?
![Ribbon_03 (2)](https://user-images.githubusercontent.com/51875622/59636734-097c2000-9133-11e9-9c3f-130c1bf1d5f1.png)

**Comment by martijnkoopman** [comment]
Hi,

Yes that's possible.
Take a look at object `openFileButton` in  `mainwindow.cpp`. 

```cpp
// Add 'Open file' button
QToolButton *openFileButton = new QToolButton(this);
openFileButton->setText(tr("File"));
openFileButton->setToolTip(tr("Open file or directory"));
openFileButton->setIcon(QIcon(":/icons/add_folder_2.svg"));

// Add dropdown menu to button
openFileButton->setPopupMode(QToolButton::MenuButtonPopup);
QMenu *menu = new QMenu("Title");
menu->addAction(QIcon(":/icons/file_2.svg"), "Recent file 1");
menu->addAction(QIcon(":/icons/file_2.svg"), "Recent file 2");
menu->addAction(QIcon(":/icons/file_2.svg"), "Recent file 3");
openFileButton->setMenu(menu);

ui->ribbonTabWidget->addButton("Project", "Import", openFileButton);
```

The button that you're supposed to add is a `QToolButton`. You can set the `popupMode` to `MenuButtonPopup` and specify a `QMenu` with `QAction`s and icons. An arrow will be visible on the button and a dropdown menu will appear when the button is clicked. You can also attach a keyboard shortcut to the actions in this dropdown menu.

More info about QToolButton: https://doc.qt.io/qt-5/qtoolbutton.html
More info about QAction: https://doc.qt.io/qt-5/qaction.html

Regards,
Martijn

**Comment by ChoiHyebin** [comment]
Hello, I have a question. How do I open a new window or dialog by click a button in the drop-down menu? Please let me know. Thank you.

<img width="92" alt="example" src="https://user-images.githubusercontent.com/91861082/159628115-2fa7943e-d5ff-4ae6-b704-168e18d3f21a.png">
