### ISSUE TITLE
Icon position in Toolbutton

### ISSUE THREAD

**Issue by ognif** [martijnkoopman/Qt-Ribbon-Widget#2]
Hello,
I added some code to your project, not yet finished to support vertical button groups, too.
Currently I have the problem that the Icon inside the TooButton is on top. There is no margin to the top border, this looks very ugly.
Do you know a way to position the icon inside the ToolButton? Like give the image a top margin of 6pix?
You can see the space problem perfect by the two selection icon.

<img width="818" alt="Screenshot 2019-06-26 at 16 09 48" src="https://user-images.githubusercontent.com/51875622/60187229-7c6d5100-982d-11e9-9e65-ee3504fea8a4.png">

**Comment by martijnkoopman** [comment]
Hi, 

You'll have to dive into the documentation of QToolButton for that, but I think that won't be possible with the standard available functions.

One (ugly) way that might work is to add some small top padding within the pixmap that is set as icon.

Another option might be to extend the class QToolButton and access some protected member variables to change its behaviour.

The third option would be to create your own Button class that supports all these features.

Regards,
Martijn
